config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => "localhost:3000"  
  resources :recipes 
  resources :comments 
  root 'recipes#index'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :users
  resources :password_resets

  get 'password_resets/edit/:id', to: 'password_resets#edit'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
    belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
    has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
    has_secure_password
    # validate :current_password, :on => :update
    # validates :password, :on => :create
    # validates :password_confirmation, presence: true, :on => :update, :unless => lambda{|user| user.password.blank?}
    before_create { generate_token(:auth_token) }
    validates_presence_of :password, :on => :create

   def send_password_reset
        generate_token(:password_reset_token)
        puts "self[column] = " +  self[:password_reset_token]
        self.password_reset_sent_at = Time.zone.now
        save!
        UserMailer.password_reset(self).deliver_now
        puts "I MADDDDDEEEE ITTTTTTTT"
    end

   def generate_token(column)
       begin
        self[column] = SecureRandom.urlsafe_base64
       end while User.exists?(column => self[column]) 
   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def require_user
     redirect_to '/login' unless current_user
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def new
        @comment = Comment.new
    end

    def index
        @comments = Comment.all
    end

    def create
        @comment = Comment.new(comment_params)
        if @comment.save
            redirect_to :back
        else
            redirect_to recipes_url
        end
    end

    
    def update
        @comment = Comment.find(params[:id])
        if @comment.update(comment_params)
            redirect_to :back
        else
            render 'edit'
        end
    end

    def destroy
        @comment = Comment.find(params[:id])
        @comment.destroy
        redirect_to :back
    end

    private 

    def comment_params
        params.require(:comment).permit!
    end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new
  end

  def create
      puts "HELLLLOOOOOO EVVVERRRYBOOODDYY"
      user = User.find_by_email(params[:email])
      puts "1---" +  user.email + " " + user.auth_token + " #{user.id}"
     user.send_password_reset  if user
      puts "1---- EMAIL DELIVERED"
    flash[:notice] = "Email sent with password rest instructions."
        redirect_to root_url   
  end

  def edit
    @user = User.find_by_password_reset_token!(params[:id])
  end

  def update
     @user = User.find_by_password_reset_token!(params[:id])
       if @user.password_reset_sent_at < 2.hours.ago
            redirect_to new_password_reset_path, :alert => "Password reset has expired."
        elsif @user.update_attributes(params[:user].permit(:password, :password_confirmation))
            redirect_to root_url, :notice => "Password has been reset!"
        else
            render :edit
        end
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
    before_action :require_user, only: [:edit, :update]

    def new 
        @recipe= Recipe.new
        puts "HEEEEEEEELLLLLLLLLLLLLLOOOOOOOO"
    end

    def index
        @recipes = Recipe.all 
    end

    def show
        @recipe =  Recipe.find(params[:id])
        @comments= Comment.all
        @comment= Comment.new
    end

    def edit
        @recipe = Recipe.find(params[:id])
    end

    def update
        @recipe = Recipe.find(params[:id])
        if @recipe.update(recipe_params)
            redirect_to @recipe
        else
            render 'edit'
        end
    end

    def destroy 
        @recipe = Recipe.find(params[:id])
        @recipe.destroy
        redirect_to root_url
    end

    def create
        @recipe = Recipe.new(recipe_params)
        if @recipe.save
            redirect_to root_url
        else
            redirect_to recipes_url
        end
    end

    private
    def recipe_params
        params.require(:recipe).permit(:name, :description, :image,  :ingredients, :directions)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    
    def new
    end

    def create
        puts params[:email]
        user = User.find_by_email(params[:session][:email])
        if user && user.authenticate(params[:session][:password])
            flash[:notice] = "Logged in!"
            session[:user_id] = user.id
            redirect_to root_url
        else
            flash.now.alert = "Invalid email or password"
            redirect_to login_url
        end
    end

    def destroy
        session[:user_id] = nil
        redirect_to root_url
    end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
    end 

    def index
        @users = User.all
    end

    def edit
        @user = User.find(params[:id])
    end

    def create 
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to root_url
        else
           redirect_to signup_url 
        end
    end

    def update
        @user = User.find(params[:id])
        user = User.find_by_email(current_user.email).try(:authenticate, params[:current_password])
        if user && @user.update_attributes(params[:user])
            redirect_to "/users"
        else
            flash.now[:error] = "Incorrect Current Password" unless user
            redirect_to "/users"
        end
    end

    private

    def user_params
        params.require(:user).permit!
    end 
end

app/helpers/ajax_helper.rb
module AjaxHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
      <nav class="top-bar" data-tobar role="navigation">
      <%= link_to "Home", "/recipes" %>
      <div class="right" >
      <% if current_user %>
            <font color="white"> <%= current_user.email %></font>
            <%= link_to "Log out", logout_path, method: "delete" %>
      <% else %>
            <%= link_to "Sign up", "/signup" %>
            <%= link_to "Log in", "/login" %>
        <% end %>
    </div>
      </nav>
      <div id="container">  
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/password_resets/edit.html.erb
<%= form_for @user, :url => password_reset_path(params[:id]) do |f| %>
    <% if @user.errors.any? %>
        <div class="error_messages">
            <h2>Form is invalid</h2>
                <ul>
                <% for message in @user.errors.full_messages %>
                    <li><%= message %></li>
                <% end %>
                </ul>
        </div>
    <% end %>
    <div class="field">
         <%= f.label :password %>
        <%= f.password_field :password %>
    </div>
    <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
    </div>
    <div class="actions"><%= f.submit "Update Password" %></div>
    <% end %>

app/views/password_resets/new.html.erb
<%= form_tag password_resets_path, :method => :post do %>
    <div>
        <%= label_tag :email %>
        <%= text_field_tag :email, params[:email] %>
    </div>
    <div><%= submit_tag "Reset Password" %></div>
<% end %>

app/views/users/edit.html.erb
<body>
    <div class="row">
    <div class="panel">
        <h3 class="centered"> Edit  <%= @user.email %></h3>
    </div>
    <div class="panel">
    <tr>
        <td>         
            <%= form_for(@user)  do |f| %>
                First Name: <%= f.text_field :first_name %>
                Last Name: <%= f.text_field :last_name %>
                New Password: <%= f.password_field :password %>
                Confirm New Password: <%= f.password_field :password_confirmation %>
                Admin: <%= f.check_box :admin %><br>
                <%= f.submit "Update" %>
            <% end %>
        </td>
    </tr>
    </div>
    </div>
</body>